version: '2'
  
services:
  sat_nginx:
    restart: always
    image: vintec/docker-nginx-php
    container_name: sat_nginx
    # user: 1000:1000
    ports:
    - "9012:80"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "../portal:/var/www:rw"
    - "./config:/etc/nginx:ro"
    - "./logs:/var/log/nginx:rw"
    - "./fpm:/etc/php5/fpm:ro"
